import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'rsuite/dist/rsuite-no-reset.min.css';
import { CustomProvider } from 'rsuite';
import "./globals.css";
import React from "react";
import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'

import Sidebar from "./components/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <main className="flex h-screen bg-gray-900 text-white">
          <Sidebar />
          <div className="flex flex-col w-full p-4 relative">
            <QueryClientProvider client={queryClient}><CustomProvider>{children}</CustomProvider></QueryClientProvider>
          </div>
        </main>
      </body>
    </html>
  );
}

